"""initial

Revision ID: 0001
Revises:
Create Date: 2024-11-05 21:40:09.744869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_categories_telegram_id'), 'categories', ['telegram_id'], unique=False)
    op.create_table(
        'closers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time', sa.Integer(), nullable=True, comment='Time in seconds'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('time'),
    )
    op.create_table(
        'reminders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time', sa.Integer(), nullable=True, comment='Time in seconds'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('time'),
    )
    op.create_table(
        'time_slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_time_slots_telegram_id'), 'time_slots', ['telegram_id'], unique=False)
    op.create_table(
        'users',
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reminder_id', sa.Integer(), nullable=True),
        sa.Column('closer_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['closer_id'],
            ['closers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['reminder_id'],
            ['reminders.id'],
        ),
        sa.PrimaryKeyConstraint('telegram_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_time_slots_telegram_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_table('reminders')
    op.drop_table('closers')
    op.drop_index(op.f('ix_categories_telegram_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
